del /s /q *.idx
del /s /q *.bak
del /s /q *.log
del /s /q *.ci
del /s /q options.txt
del /s /q output.txt
del /s /q mdrv_cmd.txt
del /s /q pre_cci.c
del /s /q combined_*.c
del /s /q password.dat
rd /s /q data
rd /s /q results
rd /s /q DfeConfig
rd /s /q result1